// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coffeeshop struct {
	ID      *int         `json:"id"`
	Name    *string      `json:"name"`
	Address *string      `json:"address"`
	Coords  *Coordinates `json:"coords"`
}

type Coordinates struct {
	X *float64 `json:"x"`
	Y *float64 `json:"y"`
}
