version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/graphql-server"
    schedule:
      interval: "weekly"
    assignees:
      - adamyeats
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    assignees:
      - adamyeats
