// Code generated by ent, DO NOT EDIT.

package coffeeshop

const (
	// Label holds the string label denoting the coffeeshop type in the database.
	Label = "coffeeshop"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldLatitude holds the string denoting the latitude field in the database.
	FieldLatitude = "latitude"
	// FieldLongitude holds the string denoting the longitude field in the database.
	FieldLongitude = "longitude"
	// Table holds the table name of the coffeeshop in the database.
	Table = "Coffeeshop"
)

// Columns holds all SQL columns for coffeeshop fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAddress,
	FieldLatitude,
	FieldLongitude,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
