// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoffeeshopColumns holds the columns for the "Coffeeshop" table.
	CoffeeshopColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "address", Type: field.TypeString},
		{Name: "latitude", Type: field.TypeFloat64},
		{Name: "longitude", Type: field.TypeFloat64},
	}
	// CoffeeshopTable holds the schema information for the "Coffeeshop" table.
	CoffeeshopTable = &schema.Table{
		Name:       "Coffeeshop",
		Columns:    CoffeeshopColumns,
		PrimaryKey: []*schema.Column{CoffeeshopColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoffeeshopTable,
	}
)

func init() {
	CoffeeshopTable.Annotation = &entsql.Annotation{
		Table: "Coffeeshop",
	}
}
