// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/adamyeats/coffeeshops/graphql-server/internal/ent/coffeeshop"
	"github.com/adamyeats/coffeeshops/graphql-server/internal/ent/predicate"
)

// CoffeeshopDelete is the builder for deleting a Coffeeshop entity.
type CoffeeshopDelete struct {
	config
	hooks    []Hook
	mutation *CoffeeshopMutation
}

// Where appends a list predicates to the CoffeeshopDelete builder.
func (cd *CoffeeshopDelete) Where(ps ...predicate.Coffeeshop) *CoffeeshopDelete {
	cd.mutation.Where(ps...)
	return cd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cd *CoffeeshopDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, CoffeeshopMutation](ctx, cd.sqlExec, cd.mutation, cd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cd *CoffeeshopDelete) ExecX(ctx context.Context) int {
	n, err := cd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cd *CoffeeshopDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(coffeeshop.Table, sqlgraph.NewFieldSpec(coffeeshop.FieldID, field.TypeInt))
	if ps := cd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cd.mutation.done = true
	return affected, err
}

// CoffeeshopDeleteOne is the builder for deleting a single Coffeeshop entity.
type CoffeeshopDeleteOne struct {
	cd *CoffeeshopDelete
}

// Where appends a list predicates to the CoffeeshopDelete builder.
func (cdo *CoffeeshopDeleteOne) Where(ps ...predicate.Coffeeshop) *CoffeeshopDeleteOne {
	cdo.cd.mutation.Where(ps...)
	return cdo
}

// Exec executes the deletion query.
func (cdo *CoffeeshopDeleteOne) Exec(ctx context.Context) error {
	n, err := cdo.cd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coffeeshop.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cdo *CoffeeshopDeleteOne) ExecX(ctx context.Context) {
	if err := cdo.Exec(ctx); err != nil {
		panic(err)
	}
}
