// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/adamyeats/coffeeshops/graphql-server/internal/ent/coffeeshop"
	"github.com/adamyeats/coffeeshops/graphql-server/internal/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeCoffeeshop = "Coffeeshop"
)

// CoffeeshopMutation represents an operation that mutates the Coffeeshop nodes in the graph.
type CoffeeshopMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	address       *string
	latitude      *float64
	addlatitude   *float64
	longitude     *float64
	addlongitude  *float64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Coffeeshop, error)
	predicates    []predicate.Coffeeshop
}

var _ ent.Mutation = (*CoffeeshopMutation)(nil)

// coffeeshopOption allows management of the mutation configuration using functional options.
type coffeeshopOption func(*CoffeeshopMutation)

// newCoffeeshopMutation creates new mutation for the Coffeeshop entity.
func newCoffeeshopMutation(c config, op Op, opts ...coffeeshopOption) *CoffeeshopMutation {
	m := &CoffeeshopMutation{
		config:        c,
		op:            op,
		typ:           TypeCoffeeshop,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withCoffeeshopID sets the ID field of the mutation.
func withCoffeeshopID(id int) coffeeshopOption {
	return func(m *CoffeeshopMutation) {
		var (
			err   error
			once  sync.Once
			value *Coffeeshop
		)
		m.oldValue = func(ctx context.Context) (*Coffeeshop, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Coffeeshop.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withCoffeeshop sets the old Coffeeshop of the mutation.
func withCoffeeshop(node *Coffeeshop) coffeeshopOption {
	return func(m *CoffeeshopMutation) {
		m.oldValue = func(context.Context) (*Coffeeshop, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m CoffeeshopMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m CoffeeshopMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *CoffeeshopMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *CoffeeshopMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Coffeeshop.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *CoffeeshopMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *CoffeeshopMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Coffeeshop entity.
// If the Coffeeshop object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CoffeeshopMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *CoffeeshopMutation) ResetName() {
	m.name = nil
}

// SetAddress sets the "address" field.
func (m *CoffeeshopMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *CoffeeshopMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the Coffeeshop entity.
// If the Coffeeshop object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CoffeeshopMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *CoffeeshopMutation) ResetAddress() {
	m.address = nil
}

// SetLatitude sets the "latitude" field.
func (m *CoffeeshopMutation) SetLatitude(f float64) {
	m.latitude = &f
	m.addlatitude = nil
}

// Latitude returns the value of the "latitude" field in the mutation.
func (m *CoffeeshopMutation) Latitude() (r float64, exists bool) {
	v := m.latitude
	if v == nil {
		return
	}
	return *v, true
}

// OldLatitude returns the old "latitude" field's value of the Coffeeshop entity.
// If the Coffeeshop object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CoffeeshopMutation) OldLatitude(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLatitude is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLatitude requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLatitude: %w", err)
	}
	return oldValue.Latitude, nil
}

// AddLatitude adds f to the "latitude" field.
func (m *CoffeeshopMutation) AddLatitude(f float64) {
	if m.addlatitude != nil {
		*m.addlatitude += f
	} else {
		m.addlatitude = &f
	}
}

// AddedLatitude returns the value that was added to the "latitude" field in this mutation.
func (m *CoffeeshopMutation) AddedLatitude() (r float64, exists bool) {
	v := m.addlatitude
	if v == nil {
		return
	}
	return *v, true
}

// ResetLatitude resets all changes to the "latitude" field.
func (m *CoffeeshopMutation) ResetLatitude() {
	m.latitude = nil
	m.addlatitude = nil
}

// SetLongitude sets the "longitude" field.
func (m *CoffeeshopMutation) SetLongitude(f float64) {
	m.longitude = &f
	m.addlongitude = nil
}

// Longitude returns the value of the "longitude" field in the mutation.
func (m *CoffeeshopMutation) Longitude() (r float64, exists bool) {
	v := m.longitude
	if v == nil {
		return
	}
	return *v, true
}

// OldLongitude returns the old "longitude" field's value of the Coffeeshop entity.
// If the Coffeeshop object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *CoffeeshopMutation) OldLongitude(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLongitude is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLongitude requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLongitude: %w", err)
	}
	return oldValue.Longitude, nil
}

// AddLongitude adds f to the "longitude" field.
func (m *CoffeeshopMutation) AddLongitude(f float64) {
	if m.addlongitude != nil {
		*m.addlongitude += f
	} else {
		m.addlongitude = &f
	}
}

// AddedLongitude returns the value that was added to the "longitude" field in this mutation.
func (m *CoffeeshopMutation) AddedLongitude() (r float64, exists bool) {
	v := m.addlongitude
	if v == nil {
		return
	}
	return *v, true
}

// ResetLongitude resets all changes to the "longitude" field.
func (m *CoffeeshopMutation) ResetLongitude() {
	m.longitude = nil
	m.addlongitude = nil
}

// Where appends a list predicates to the CoffeeshopMutation builder.
func (m *CoffeeshopMutation) Where(ps ...predicate.Coffeeshop) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the CoffeeshopMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *CoffeeshopMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Coffeeshop, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *CoffeeshopMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *CoffeeshopMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Coffeeshop).
func (m *CoffeeshopMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *CoffeeshopMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.name != nil {
		fields = append(fields, coffeeshop.FieldName)
	}
	if m.address != nil {
		fields = append(fields, coffeeshop.FieldAddress)
	}
	if m.latitude != nil {
		fields = append(fields, coffeeshop.FieldLatitude)
	}
	if m.longitude != nil {
		fields = append(fields, coffeeshop.FieldLongitude)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *CoffeeshopMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case coffeeshop.FieldName:
		return m.Name()
	case coffeeshop.FieldAddress:
		return m.Address()
	case coffeeshop.FieldLatitude:
		return m.Latitude()
	case coffeeshop.FieldLongitude:
		return m.Longitude()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *CoffeeshopMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case coffeeshop.FieldName:
		return m.OldName(ctx)
	case coffeeshop.FieldAddress:
		return m.OldAddress(ctx)
	case coffeeshop.FieldLatitude:
		return m.OldLatitude(ctx)
	case coffeeshop.FieldLongitude:
		return m.OldLongitude(ctx)
	}
	return nil, fmt.Errorf("unknown Coffeeshop field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CoffeeshopMutation) SetField(name string, value ent.Value) error {
	switch name {
	case coffeeshop.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case coffeeshop.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case coffeeshop.FieldLatitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLatitude(v)
		return nil
	case coffeeshop.FieldLongitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLongitude(v)
		return nil
	}
	return fmt.Errorf("unknown Coffeeshop field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *CoffeeshopMutation) AddedFields() []string {
	var fields []string
	if m.addlatitude != nil {
		fields = append(fields, coffeeshop.FieldLatitude)
	}
	if m.addlongitude != nil {
		fields = append(fields, coffeeshop.FieldLongitude)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *CoffeeshopMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case coffeeshop.FieldLatitude:
		return m.AddedLatitude()
	case coffeeshop.FieldLongitude:
		return m.AddedLongitude()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *CoffeeshopMutation) AddField(name string, value ent.Value) error {
	switch name {
	case coffeeshop.FieldLatitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLatitude(v)
		return nil
	case coffeeshop.FieldLongitude:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLongitude(v)
		return nil
	}
	return fmt.Errorf("unknown Coffeeshop numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *CoffeeshopMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *CoffeeshopMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *CoffeeshopMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Coffeeshop nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *CoffeeshopMutation) ResetField(name string) error {
	switch name {
	case coffeeshop.FieldName:
		m.ResetName()
		return nil
	case coffeeshop.FieldAddress:
		m.ResetAddress()
		return nil
	case coffeeshop.FieldLatitude:
		m.ResetLatitude()
		return nil
	case coffeeshop.FieldLongitude:
		m.ResetLongitude()
		return nil
	}
	return fmt.Errorf("unknown Coffeeshop field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *CoffeeshopMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *CoffeeshopMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *CoffeeshopMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *CoffeeshopMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *CoffeeshopMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *CoffeeshopMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *CoffeeshopMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Coffeeshop unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *CoffeeshopMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Coffeeshop edge %s", name)
}
