// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Coffeeshop is the predicate function for coffeeshop builders.
type Coffeeshop func(*sql.Selector)
